github_link: https://github.com/xnum/8591Helper
store_link: https://chrome.google.com/webstore/detail/8591%E5%B0%8F%E5%B9%AB%E6%89%8B/embdikfflbaidhilnilnbkobojbjikia?utm_source=chrome-app-launcher-info-dialog
theme: jekyll-theme-slate